name: Integration Tests & Code Style

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, experimental-recent-changes ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Download conda env info for qiime2 amplicon 2024.5
      run: |
        curl -L https://data.qiime2.org/distro/amplicon/qiime2-amplicon-2024.5-py39-linux-conda.yml -o environment.yml
        echo "name: qp-platemapper" > named_env.yml
        cat environment.yml >> named_env.yml

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.9
        channels: conda-forge
        activate-environment: qp-platemapper
        environment-file: named_env.yml

    - name: Add additional dependencies
      shell: bash -el {0}  # https://github.com/conda-incubator/setup-miniconda?tab=readme-ov-file#important
      run: |
        conda install pytest-cov flake8 -y

    - name: Lint with flake8
      shell: bash -el {0}
      run: |
        flake8 platemapper/

    - name: Execute tests
      shell: bash -el {0}
      run: |
        pip install -e .
        pytest --cov=platemapper --cov-report=lcov

    - name: Send coverage report to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "coverage.lcov"
