name: Integration Tests & Code Style

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Download conda env info for qiime2 amplicon 2024.5
      run: |
        curl -L https://data.qiime2.org/distro/amplicon/qiime2-amplicon-2024.5-py39-linux-conda.yml -o environment.yml
        echo "name: qp-platemapper" > named_env.yml
        cat environment.yml >> named_env.yml

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.9
        channels: conda-forge
        activate-environment: qp-platemapper
        environment-file: named_env.yml

    - name: Add additional dependencies
      run: |
        conda install pytest-cov -y

    - name: Execute tests
      run: |
        pwd
        conda list
        echo $CONDA_PREFIX
        find / -name "*pytest*" 2> /dev/null
        /usr/share/miniconda/envs/qp-platemapper/bin/pytest



    # - name: Setup for conda
    #   uses: conda-incubator/setup-miniconda@v2
    #   with:
    #     auto-update-conda: true
    #     python-version: '3.9'

    # - name: Install dependencies
    #   run: |
    #     conda config --add channels defaults
    #     conda config --add channels conda-forge
    #     conda config --add channels bioconda
    #     conda init
    #     conda deactivate
    #     source /home/runner/.bashrc
    #     conda env create -n qp-platemapper --file https://data.qiime2.org/distro/amplicon/qiime2-amplicon-2024.5-py39-linux-conda.yml
    #
    #
    # - name: Generate Ordination Layouts
    #   run: |
    #     tmpdir=`~/temp`
    #     mkdir -p $tmpdir
    #     cd $tmpdir && python -c 'print("Hallo")' > test.txt
    #
    # # - name: Lint with flake8
    # #   run: |
    # #     $CONDA/bin/flake8 src/marbel/
    #
    # - name: Archive results
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ordinations
    #     path: ~/temp

    # - name: Run tests with pytest
    #   run: |
    #     $CONDA/bin/pytest . --ignore=tests/test_functional.py --doctest-modules --cov=src/marbel --cov-report=lcov
    # - name: Send coverage report to Coveralls
    #   uses: coverallsapp/github-action@master
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     path-to-lcov: "coverage.lcov"
